## Printing

In [4]:
print("Hello, World")

Hello, World


## Types

In [5]:
s = "I am a String"

In [6]:
i = 55 # <- this is an integer
print(type(i))

<class 'int'>


In [7]:
f = 2. # <- this is a float
print(type(f))

<class 'float'>


In [8]:
print(f+i)
print(f-i)
print(f*i)
print(i/f)
print(i//f)

57.0
-53.0
110.0
27.5
27.0


In [9]:
l = [1,2,3,"5"]
print(l)

[1, 2, 3, '5']


In [10]:
len(l)

4

In [11]:
l.append(4)

In [12]:
l

[1, 2, 3, '5', 4]

In [13]:
l[0:4:2]

[1, 3]

In [14]:
t = (1,2,3)
print(t)
t.append(3)

(1, 2, 3)


AttributeError: 'tuple' object has no attribute 'append'

In [15]:
d = {1:'2', 'a':'hello'}
print(d)

{1: '2', 'a': 'hello'}


In [16]:
d[1]=4

In [17]:
d

{1: 4, 'a': 'hello'}

In [18]:
b = True
print(b, int(b))
b = False
print(b, int(b))

True 1
False 0


## Loops and Conditions

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
i = 0
while i<10:
    print(i)
    i += 1

0
1
2
3
4
5
6
7
8
9


In [ ]:
statement = "RL is cool"
if statement == "RL is cool":
    print("hey, RL is cool")
else:
    print("yaboring")

hey, RL is cool


## Functions

In [ ]:
def f(a,b):
    return a+b

print(f("RL", " is cool"))

RL is cool


## Classes

In [ ]:
class RL:
    test = 5
    def __init__(self):
        print("RL class being initialized")
        self.cool = True
    def is_cool(self):
        return True
    def __len__(self):
        return 5
    
rl = RL()
len(rl)
print("RL is cool?", rl.is_cool())

RL class being initialized
RL is cool? True


## Cool commands

In [ ]:
l = list(range(10))
print(l)
filtered = [elem for elem in l if elem % 2 == 0]
print(filtered)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8]


In [ ]:
filtered_dict = {i:v for i,v in enumerate(filtered)}
print(filtered_dict)

{0: 0, 1: 2, 2: 4, 3: 6, 4: 8}


In [ ]:
l1 = [1,2,3,4,5]
print(l1)
l2 = [i*5 for i in l1]
print(l2)

[1, 2, 3, 4, 5]
[5, 10, 15, 20, 25]


In [ ]:
zipped = list(zip(l1,l2))
print(zipped)

[(1, 5), (2, 10), (3, 15), (4, 20), (5, 25)]


In [ ]:
unzipped = list(zip(*zipped))
print(unzipped)

[(1, 2, 3, 4, 5), (5, 10, 15, 20, 25)]


In [ ]:
l = [1,2,3,4]
l2 = [1,2,*l]

In [ ]:
l2

[1, 2, 1, 2, 3, 4]

In [ ]:
d ={'first':1,'second':2}

In [ ]:
f(**d)

f(first=1, second=2)

TypeError: f() got an unexpected keyword argument 'first'

In [ ]:
d = {'a':1,'b':2}

print(f(**d))
print(f(a=1,b=2))

3
3


## Numpy

https://numpy.org/doc/stable/

In [ ]:
import numpy as np

In [ ]:
m1 = np.array([[1,2,3],[4,5,6]])

In [ ]:
ones = np.ones((3,4))

In [ ]:
np.diag((4,3))

array([[4, 0],
       [0, 3]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
print(m1)
print(m1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
print(ones)
print(ones.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)


In [ ]:
print(m1.T)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
print(m1@ones)

[[ 6.  6.  6.  6.]
 [15. 15. 15. 15.]]


In [ ]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(m1.mean(), m1.mean(axis=0), m1.mean(axis=1))

3.5 [2.5 3.5 4.5] [2. 5.]


In [ ]:
print(m1+5.)

[[ 6.  7.  8.]
 [ 9. 10. 11.]]


In [ ]:
print(m1*5)

[[ 5 10 15]
 [20 25 30]]


## Torch

https://pytorch.org/docs/stable/torch.html

In [ ]:
import torch

In [ ]:
m1 = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float)

In [ ]:
ones = torch.ones((3,4))

In [ ]:
print(m1)
print(m1.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [ ]:
print(ones)
print(ones.shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.Size([3, 4])


In [ ]:
print(m1.T)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [ ]:
print(torch.matmul(m1,ones))

tensor([[ 6.,  6.,  6.,  6.],
        [15., 15., 15., 15.]])


In [ ]:
print(m1.mean(), m1.mean(axis=0), m1.mean(axis=1))

tensor(3.5000) tensor([2.5000, 3.5000, 4.5000]) tensor([2., 5.])


In [ ]:
print(m1+5)

tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.]])


In [ ]:
print(m1*5)

tensor([[ 5., 10., 15.],
        [20., 25., 30.]])


In [ ]:
m1.long()

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
m1.float()

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
m1.double()

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [ ]:
m1.bool()

tensor([[True, True, True],
        [True, True, True]])

In [ ]:
m1>3

tensor([[False, False, False],
        [ True,  True,  True]])

In [ ]:
m1[m1>3]

tensor([4., 5., 6.])

In [ ]:
torch.where(m1>3)

(tensor([1, 1, 1]), tensor([0, 1, 2]))

In [ ]:
m1[:1,:]

tensor([[1., 2., 3.]])